### ISSUE TITLE
traduçao errada

### ISSUE THREAD

**Issue by Lucas559-noob** [Ludeon/RimWorld-PortugueseBrazilian#116]
no jogo eu vi algo sobre o quarto, a versão em ingles seria essa: `minhoca's room` e em português esta como: `minhoca de quarto` 
provavelmente no arquivo o texto é algo tipo `{pawn} room` e traduzindo, a única coisa que iria traduzir seria "room"

**Comment by ElioNETO-trad** [comment]
Olá,

estou tentanto encontrar essa string, mas não estou achando.  Você pode dar mais informações ?

O problema é que tenho a sensação que estou trabalhando sozinho neste projeto (embora não trabalho há uns 2-3 meses por falta de tempo). A tradução do último update está finalizada, precisamos de pessoas para fazer a correção / revisão.

**Comment by goliv04053** [comment]
Seria possível você mandar uma captura de tela disso?

**Comment by goliv04053** [comment]
Achei. Dá uma olhada no Misc.xml. Linha 143

**Comment by ElioNETO-trad** [comment]
Opa, normalmente consegui arrumar. Mudei a ordem da pessoa e do quarto, ficando (seguindo o seu exemplo) : "Quarto de minhoca".

Vejam se funcionou! 


Elio NETO

**Comment by Lucas559-noob** [comment]
achei outro erro
`
![image](https://user-images.githubusercontent.com/54007604/113577797-30e9f880-95f8-11eb-9256-e0db460b8dda.png)
`
deveria ser usado A caravana de {pawn} foi formada... e acho que a palavra encomendas seria melhor trocar por destino/objetivo

**Comment by ElioNETO-trad** [comment]
Tentei fazer essa mudança, mas o problema que o "Taizoz caravanas" é representado por um {0}. Eu não sei muito bem a que isso se refere, tenho que buscar. Tentei mudar de ordem e também mudei "encomendas" para "Objetivos".

Elio NETO

**Comment by Lucas559-noob** [comment]
> Tentei fazer essa mudança, mas o problema que o "Taizoz caravanas" é representado por um {0}. Eu não sei muito bem a que isso se refere, tenho que buscar. Tentei mudar de ordem e também mudei "encomendas" para "Objetivos".
> 
> Elio NETO

Taizoz é o nome do pawn "líder" da caravana

**Comment by ElioNETO-trad** [comment]
Sim, a questão é que não sei muito bem como modificar o {0}, já que é uma call para outro código. Vou perguntar no Discord oficial do Rimworld na parte de traduções.

Por enquanto, adicionei um artigo e passei pro feminino, ficando : "A {0} foi formada e agora está viajando pelo mundo"
