### ISSUE TITLE
Erro carregando créditos

### ISSUE THREAD

**Issue by Lucas559-noob** [Ludeon/RimWorld-PortugueseBrazilian#118]
ao iniciar, na janela de contribuidores com a tradução não aparece ninguém
https://gist.github.com/aec1dea3385df330d673e5f974eea8be

**Comment by ElioNETO-trad** [comment]
![Rimworld_mainscreen](https://user-images.githubusercontent.com/69966337/113619632-83a7cc80-9659-11eb-8230-b415aca1ea57.PNG)


No meu está aparecendo, você pode mandar o seu relatório gerado pela tradução ?

Caso esteja usando a tradução do Rimworld pela própria STEAM, acredito que as modificações que estamos fazendo estarão disponíveis a partir do próximo patch pela Ludeon.

Elio NETO

**Comment by Lucas559-noob** [comment]
> ![Rimworld_mainscreen](https://user-images.githubusercontent.com/69966337/113619632-83a7cc80-9659-11eb-8230-b415aca1ea57.PNG)
> 
> No meu está aparecendo, você pode mandar o seu relatório gerado pela tradução ?
> 
> Caso esteja usando a tradução do Rimworld pela própria STEAM, acredito que as modificações que estamos fazendo estarão disponíveis a partir do próximo patch pela Ludeon.
> 
> Elio NETO

é que eu tenho a versão 1.2.2900, e la não aparece

**Comment by ElioNETO-trad** [comment]
Entendi,

eu havia esquecido, mas no patch anterior estava com esse problema justamente na linha 84, com um double </li>. Já foi corrigido. Você está usando a tradução direto do Github ou da Steam?

**Comment by Lucas559-noob** [comment]
> Entendi,
> 
> eu havia esquecido, mas no patch anterior estava com esse problema justamente na linha 84, com um double . Já foi corrigido. Você está usando a tradução direto do Github ou da Steam?

a que veio junto com o download da steam

**Comment by ElioNETO-trad** [comment]
Então normalmente no próximo patch estará arrumado.

Elio NETO
