### ISSUE TITLE
Novas Backstories

### ISSUE THREAD

**Issue by hcmello** [Ludeon/RimWorld-PortugueseBrazilian#12]
A nova build A16-unstable permite gerar um catálogo com as novas backstories a serem traduzidas.
já existe alguém trabalhando nelas?

**Comment by ArxdSilva** [comment]
@hcmello ainda nao começamos

**Comment by VitorGlinski** [comment]
@ArxdSilva Saberia me dizer onde eu encontro os arquivos originais em inglês? Posso então começar a traduzir assim que eu puder.

**Comment by ArxdSilva** [comment]
O mais confiável é usar o arquivo em inglês provido pelo jogo, cujo caminho no seu pc é:

(PastaDoJogo)/Mods/Core/Languages/en-US.

**Comment by VitorGlinski** [comment]
Obrigado!
