### ISSUE TITLE
Tradução da nova DLC

### ISSUE THREAD

**Issue by ABFrozza** [Ludeon/RimWorld-PortugueseBrazilian#127]
Fala pessoal blz

Comecei a jogar RimWorld há uns dois meses e agora com essa nova DLC gostaria de ajudar a fazer a tradução ainda estou aprendendo a usar aqui o site e o software, ainda tem alguém ai ativo?

**Comment by ElioNETO-trad** [comment]
Olá,

Eu vou voltar a trabalhar nesta DLC, terminei de traduzir a última praticamente sozinho, mas não revisei. Vou fazer um grupo no Discord

**Comment by The-Geovanni** [comment]
Olá,

Também pretendo ajudar na tradução desta DLC o máximo possível!

**Comment by ElioNETO-trad** [comment]
Olá, 

Eu estou separando os arquivos e vou adicionar os TODO o mais rápido possível, os Keyed são fáceis, o problema são os arquivos Defs, já que temos que criar os arquivos a partir do 0.

Eu estou terminando de configurar o grupo no Discord, já mando o link

**Comment by ElioNETO-trad** [comment]
Link do discord : https://discord.gg/RZEvDtDG


Vou atualizando o grupo com o tempo

**Comment by ABFrozza** [comment]
Dei uma lida no geral e vi algumas coisa que talvez de pra mudar, eu ainda estou tentando intender como faz pra mexer nos programas então quem já tiver pratica e já puder ver acho melho

Barbicha está escrito com x o correto é ch
os dizeres para os transhumanistas no jogo está em inglês
e a descrição da barba à moda lincoln está estranha, acho que da pra deixar à moda lincoln
