### ISSUE TITLE
TODO Ideology + 1.3

### ISSUE THREAD

**Issue by ElioNETO-trad** [Ludeon/RimWorld-PortugueseBrazilian#129]
Todos os TODO da expansão Ideology + 1.3 estão disponíveis conforme o TranslationReport.

Atualizem os seus respectivos repositórios antes de trabalhar nas traduções!

Boa tradução!

**Comment by ElioNETO-trad** [comment]
Como trabalhar com TODO está no Discord do grupo.

**Comment by KitsuneModder** [comment]
Tem um Discord??
