### ISSUE TITLE
Colonia ou Colonização

### ISSUE THREAD

**Issue by VitorGlinski** [Ludeon/RimWorld-PortugueseBrazilian#13]
Olá, gostaria de trazer a discussão o tema do emprego dos termos Colônia e Colonização no RimWorld. Uma vez que é uma tradução realizada por muitos membros (ativos ou não) deve se entrar em acordo com qual termo vai ser empregado de agora em diante - visando que o termo não mude a cada atualização que o jogo venha a ter.

**Comment by VitorGlinski** [comment]
Em minha opinião o termo deveria ser Colônia, por ser algo que está ocorrendo e não um "feito do passado" como a Colonização do Brazil, realizada por Portugal por exemplo.

**Comment by ArxdSilva** [comment]
Eu concordo, ainda mais visto que no próprio jogo é utilizada a frase: "Um simulador de colônia por Tynan Sylvester"
