### ISSUE TITLE
Dxa eu falar um bglh

### ISSUE THREAD

**Issue by Cabodo** [Ludeon/RimWorld-PortugueseBrazilian#14]
Eu tô inativo aq no GitHub da Ludeon faz uns 3 meses, pq eu resolvi fazer uma coisa: Eu catei o file en-US e tô passando ele inteiro pra português. Eu só vou fazer alguma coisa quando terminar tudo. Eu tô traduzindo sem nenhum erro de português, no maximo erros de digitação (Sim, eu tô usando até colocações pronominais e etc, mas não tô usando aquelas palavras escrotas que geralmente aparecem em traduções de jogos, como "Nascer" no lugar de "Spawnar"). Tô fazendo essa Isaura pra saber de vocês. Quando eu tiver terminado, vocês vão querer que eu publique aqui? (Sim, antes eu vou revisar todo o conteúdo já publicado por traduções melhores) Se não, eu vou fazer uso próprio dela mesmo, se sim, revisa tudo pra ver se não tem nenhum erro e pá.

**Comment by Cabodo** [comment]
(+) Quaisquer ideias, só postar aq nos comentários
(+) Se todos concordarem, eu vou focar mais em traduzir e provavelmente vai ficar pronta até o meio do ano

**Comment by Srlimao** [comment]
Eu dei uma parada quando mudou a estrutura dos arquivos, meio que cagou tudo ausauhs

**Comment by ArxdSilva** [comment]
@cabodo o melhor é você fazer e ir adicionando gradualmente, pois pode ocorrer como o @srlimao falou de mudar as estruturas e todo o seu trabalho fica inválido

**Comment by Cabodo** [comment]
O sistema Keyed é bem mais fácil que o DefInjected, e a PortugueseBrazillian é uma das únicas traduções que ainda tem (mesmo bem antigas) traduções sentadas em DefInjected...

**Comment by Cabodo** [comment]
@arxdsilva Se mudar aí pelo menos eu já tenho as traduções prontas, até pq nas traduções atuais tem muita coisa errada, aí é só passar as traduções pro novo modelo

**Comment by Srlimao** [comment]
Exato, por isso tem q pegar o último arquivo lá em inglês, os q tinha aqui na última vez tava beeeeem ultrapassado :c

**Comment by Cabodo** [comment]
@srlimao eu peguei o inglês e tô passando ele pra português enquanto reviso os atuais

**Comment by ArxdSilva** [comment]
@cabodo o problema é que para achar para onde foram movidas as tags já traduzidas ou se elas foram modificadas, você teria um trabalhão manual

**Comment by Srlimao** [comment]
Boa, fez a mão de atualizar os ToDo? Tô afim de pegar algo pra ajudar

**Comment by Cabodo** [comment]
Eu não mexi nos "ToDo", eu só peguei o arquivo en-US do meu jogo e tô passando ele inteiro pra português :|

**Comment by ArxdSilva** [comment]
@cabodo, não dá pra fazer assim, pois vai quebrar/ignorar muita coisa que já está traduzido. 

Para que traduzir seja mais fácil a todos e colaborativo, todos precisam fazer suas traduções em uma ramificação deste projeto (diretório PT-BR) e só usar o original em inglês como base de comparação, pois assim vai sobrescrever muita coisa já feita.

**Comment by Cabodo** [comment]
@arxdsilva exatamente por isso que eu fiz essa issue. Lá na issue tá escrito que eu revisei todas as outras traduções (e até usei algumas que achei melhor).

**Comment by ronaldiux** [comment]
@Cabodo  eu tive um problema que eu traduzi boa parte em uma versao e as tags mudaram e perdi mt coisa kkk , se quiser dividir o trabalho estou aqui

**Comment by Cabodo** [comment]
@ronaldiux se for pra dividir, termina às DefInjected, pq Keyed já tá 75% pronto :|

**Comment by ronaldiux** [comment]
@Cabodo vc ja esta usando os arquivos da versao 16 ?

**Comment by Cabodo** [comment]
@ronaldiux tô usando os da 15, inserindo tudo de novo da 16. Não alterou nada, só adicionou

**Comment by ronaldiux** [comment]
Ah blz, vo pegar os da 16 msm e vo começar as Definjected....

**Comment by ArxdSilva** [comment]
Enviem suas contribuições aos poucos por favor, assim facilita o trabalho de quem vai revisar

**Comment by ronaldiux** [comment]
Galera, enquanto fui atras da versao 16, achei uma tradução (link - https://www.dropbox.com/s/346fjm5w6jly4mu/Rimworld%20PT-BR%20%284.1%29%20%28Alpha%2016%29.zip?dl=0 ) estou testando ela, esta bem perfeita ate o momento, e pelo que vi nos arquivos esta completa, descobri que o criador tem uma pagina no facebook especifica para o assunto, acho que podemos pegar essa como base e continuar dando os updates a partir deste.

**Comment by WeslleyNasRocha** [comment]
Bom, eu sei que eu estou um pouco inativo por aqui, mas mesmo assim, não acho que seja somente "pegar" e continuar. Se você quer usar essa tradução como base, primeiro tem que entrar em contato com o autor do mesmo, pra saber se ele autoriza.

**Comment by ronaldiux** [comment]
@WeslleyNasRocha ja fiz isso, ele aceitou claro que com os creditos dele.
E eu ja testei ela esta completa (ja na versao 16), se os outros quiserem baixem e vejam como a tradução br contida aqui no github esta muito atrasada e cheia de erros, poderiamos usar essa já.

**Comment by Cabodo** [comment]
>só um aviso, tô quase terminando as Keyed, vou começar a postar amanhã provavelmente

**Comment by WeslleyNasRocha** [comment]
@ronaldiux aaaa, então é só alegria, e tradução ksksks

**Comment by ArxdSilva** [comment]
Pra quem quiser contribuir, veja o PR https://github.com/Ludeon/RimWorld-PortugueseBrazilian/pull/15
