### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by LoboMetalurgico** [Ludeon/RimWorld-PortugueseBrazilian#192]
Olá Tradutores,

Eu realmente gostaria de ter um contato maior com todos, para podermos nos organizar mais facilmente e discutir assuntos importantes. Vi que no readme temos um discord, mas o link expirou. Alguém aqui faz parte dele e consegue emitir um link atualizado ou ele é apenas um discord morto?

Atenciosamente,
LoboMetalurgico

**Comment by KitsuneModder** [comment]
https://discord.gg/JYhMBbR7v3

;)

**Comment by LoboMetalurgico** [comment]
Obrigado! :)
