### ISSUE TITLE
Ideologia - Não 'Role'

### ISSUE THREAD

**Issue by Lucas559-noob** [Ludeon/RimWorld-PortugueseBrazilian#223]
# 😵 Encontrei um Erro
No arquivo Thoughts_IdeoRole.xml, possui um erro que é visível no jogo, a parte de um pawn ser líder mas ao mesmo tempo ter o "Não 'Matador'", "Não 'Boxeador'", se refere que ele tbm queria ser algum desse role, mas a palavra 'no {role}' tbm pode ser vista como sem {role}, o que seria ideal

### 📝 Etapas de Reprodução

1. Acesse o menu de humor/necessidade
2. Certifique que ja seja um Líder
3. Veja o texto no humor negativo.

### 📜 Informações de Depuração

* ✍️ Versão do RimWorld: 1.3.3200
* ✍️ Está usando a tradução nativa?: sim

**Comment by Kitsune912** [comment]
Correção feita!

Obrigado.
