### ISSUE TITLE
Tradução da Build 17

### ISSUE THREAD

**Issue by Tallysbta** [Ludeon/RimWorld-PortugueseBrazilian#23]
Pessoal, sei que a versão 17 ainda está sendo desenvolvida, também vi que alguém fez um pull request da tradução porém foi negada. Podemos ir trabalhando nessa tradução ou seria interessante esperar um pouco e ver se a pessoa que fez a tradução irá se juntar a nós?

**Comment by ArxdSilva** [comment]
Oi @Tallysbta , podemos sim! A melhor maneira de fazer é criar uma ramificação deste projeto para o desenvolvimento da tradução do alpha 17 que só será mergeado depois do lançamento oficial (para evitar conflitos com quem já está usando a do alpha 16).

**Comment by Tallysbta** [comment]
Opa maravilha!, Vou começar então.
