### ISSUE TITLE
Progresso do projeto

### ISSUE THREAD

**Issue by FlyingRockbass** [Ludeon/RimWorld-PortugueseBrazilian#4]
Prezados, bom dia.

Eu gostaria de saber como está o progresso da tradução, pois gostaria de contribuir para a mesma. Já jogo o jogo a muito tempo, e quero contribuir na tradução.

Caso o projeto tenha sido descontinuado, gostaria de utilizar os dados já colocados aqui para continuar a tradução.

For English viewers, I wrote that I want to know the status of this translation so that if it is stopped, I would resume it.

**Comment by Hcgc3** [comment]
Bom dia

Poderas fazer parte da equipa porque um membro novo e sempre bem vindo.

So teras que saber programar em XML mas será muito facil de saber o que
fazer.

Obrigado

No dia quarta-feira, 18 de maio de 2016, FlyingRockbass <
notifications@github.com> escreveu:

**Comment by WeslleyNasRocha** [comment]
Eu também gostaria de participar da tradução.

**Comment by xGlenio** [comment]
Fui adicionado hoje e queria contribuir com o projeto de tradução. Nunca traduzi um jogo, mas não parece complicado. Existe algum canal para se comunicar com o time?

**Comment by ArxdSilva** [comment]
@xGlenio ainda nao, mas podemos pensar em criar um. Acredito que por enquanto o melhor é usarmos o fórum mesmo

**Comment by Cesth** [comment]
Por favor, retirar o meu email do processo de tradução e do recebimento de emails por parte do GitHub.

Obrigado,


_______________________________________________

César Soares de Oliveira


Em 29 de outubro de 2016 às 10:07:15, Arthur Silva (notifications@github.com<mailto:notifications@github.com>) escreveu:

@xGlenio<https://github.com/xGlenio> ainda nao, mas podemos pensar em criar um. Acredito que por enquanto o melhor é usarmos o fórum mesmo

**Comment by ArxdSilva** [comment]
@Cesth voce precisa sair pelo Github da Organização

**Comment by OliveiraW** [comment]
Comecei hoje e vi no repositório de PT/BR que existe muito texto em português europeu.
O que preciso saber antes de começar a alterar os textos das chaves?
...tipo politica do grupo ou recomendações.

**Comment by ArxdSilva** [comment]
@OliveiraW ainda nao criamos um arquivos de boas praticas mas seria interessante, criei a Issue #9 para isso, pode adicionar na pasta principal o arquivo e contribuir com ele se quiser; Caso queira discutir mais sobre isso use a nova Issue (:

**Comment by ArxdSilva** [comment]
@OliveiraW , não existe por enquanto nenhum padrao mas peço que como ainda não temos muitos membros ativos, ao executar mudanças não enviar direto a esse repositório. Faça um fork no seu pessoal e depois um pull request, que aí eu reviso as alterações e agt corrige ou não o que precisar.

**Comment by OliveiraW** [comment]
@ArxdSilva, no caso de múltiplos membros, seria bom definir trechos para cada um.
ou de qualquer maneira quer me indicar um ponto de inicio para ser mais proveitoso do que revisão?

**Comment by ArxdSilva** [comment]
@OliveiraW , tem bastante tempo que outros membros não participam da tradução, então acredito que qualquer local que você decidir contribuir já ajuda em muito. A revisão será só para novas adições de tradução; 

Indico que você comece carregando o jogo em português e colocando em modo Desenvolvedor para ver o que está quebrado na tradução (pode acreditar, tem bastante coisa errada). A partir daí você vai ser capaz de pesquisar os nomes que estão quebrados no projeto e corrigir a tradução ou as tags erradas.

Se você souber um pouco de programação e quiser automatizar um pouco algumas coisas tenho um projeto já semi-funcional para ajudar a galera na tradução: [XML-Comp](https://github.com/arxdsilva/xml-comp)

**Comment by lichbeoulve** [comment]
o pq nao estou participando mais da traduçao, foi por ter fechado o jogo e nao ter visto nos creditos os tradutores brasileiros, ai eu perdi a vontade de ajudar eles. nao sei se isso mudou, mas ultima vez que busquei nao vi credito algum

**Comment by ArxdSilva** [comment]
@lichbeoulve acredito que os creditos devem ser atualizados a cada versao nova do jogo entao em breve deve mudar, de qualquer forma vou cobrar os Devs esse assunto.

**Comment by jasondayshi** [comment]
tambem quero ajudar alguem que me explique como posso fazer??

**Comment by ronaldiux** [comment]
Olá, ja estou inscrito aqui tem um tempinho mas nao me envolvia pois estava sem um pc... agr quero começar a traduzir, pelo que eu baixei é so substituir as palavras ou tem coisas a mais ? rsrssssssssrrsrs

**Comment by ArxdSilva** [comment]
@ronaldiux recomendo começar lendo o nosso [Manual de Boas Práticas](https://github.com/Ludeon/RimWorld-PortugueseBrazilian/blob/master/boasPraticas.md).

**Comment by ronaldiux** [comment]
Eu li, mas nao me deu nenhuma ajuda no que eu devo fzr para traduzir... ja instalei o github desktop e baixei os arquivos, e fui substituindo tudo o que eu encontrei em ingles e coloquei em portugues de acordo com o que achei que ficaria melhor, logo mais vou testar e enviar no pull request.
