### ISSUE TITLE
Nossa pasta RulePackDef não funciona na parte de prisioneiro

### ISSUE THREAD

**Issue by RafaelReifel** [Ludeon/RimWorld-PortugueseBrazilian#48]
sempre que vai usar uma tradução de lá, sempre é ignorado e fica em inglês

talvez tenha que ativar o uso dela de algum jeito

caminho: DefInjected\RulePackDef

notei quando tava mexendo no arquivo Interactions_Prisoner.xml

**Comment by RafaelReifel** [comment]
@arxdsilva tu pode ajudar aqui? xP

**Comment by arxdsilva** [comment]
@RafaelReifel assim que chegar em casa eu testo e te dou um feedback de como podemos usar isso. Pode ser um erro de nome da pasta ou algo do tipo

**Comment by RafaelReifel** [comment]
ajeitei, peguei o arquivo da russia, e editei em cima, e eles nao usaram o nome de quem foi interagir com o prisioneiro
