### ISSUE TITLE
Ajuda

### ISSUE THREAD

**Issue by WeslleyNasRocha** [Ludeon/RimWorld-PortugueseBrazilian#5]
Eu so queria saber uma coisa, os arquivos que necessitam da tradução estão em keyed ou definjectec?

**Comment by Cabodo** [comment]
A tradução já está em andamento. Não sei mexer nos definjected então só mexo com os keyed, e neles tem coisa mal traduzida é coisa mal traduzida. Veja e reveja todos os arquivos pra tentar melhorar a tradução, mas antes confira os arquivos já postados aqui que aguardam o próximo update do RimWorld.

**Comment by Srlimao** [comment]
Acredito q os arquivos estão super desatualizados nao? falta algumas pastas acho

**Comment by Srlimao** [comment]
Logo mais atualizarei o que falta

**Comment by ArxdSilva** [comment]
@WeslleyNasRocha, os arquivos a serem traduzidos estão tanto na pasta 'Keyed' quanto 'Definjected', os conteúdos de cada pasta é diferente, por isso a distinção. Sinta-se livre para ajudar na parte que se sentir mais confortável.
