### ISSUE TITLE
progresso tradução

### ISSUE THREAD

**Issue by brunotdantas** [Ludeon/RimWorld-PortugueseBrazilian#59]
Olá Pessoal, tudo bem? 

Me interessei pelo projeto, gostaria de saber se ainda há textos a traduzir, se sim, se poderia fazer parte do time. 

Obrigado

**Comment by arxdsilva** [comment]
Boa tarde Bruno!

Sempre tem algo faltando ou a ser melhorado. Existe um 'processo' pra entrar no time que foi estabelecido pelo @TynanSylvester, se nao me engano basta vc mandar um email pedindo para participar.

Abs

**Comment by arxdsilva** [comment]
https://ludeon.com/forums/index.php?topic=2933.0
