### ISSUE TITLE
Alguém ainda está ativo na tradução do RimWorld?

### ISSUE THREAD

**Issue by Hokys** [Ludeon/RimWorld-PortugueseBrazilian#61]
Olá, queria saber se alguém ainda é ativo na tradução do RimWorld para Português brasileiro.
Vejo que as últimas modificações nos arquivos da tradução do jogo foram eu quem fez... Alguém poderia se pronunciar?

**Comment by homerbra** [comment]
Olá, eu ainda estou ativo e posso ajudar na tradução, eu ajudei a traduzir mods de Rimworld, mas eu posso ajudar nesse novo projeto sem problema algum.

**Comment by Hokys** [comment]
> Olá, eu ainda estou ativo e posso ajudar na tradução, eu ajudei a traduzir mods de Rimworld, mas eu posso ajudar nesse novo projeto sem problema algum.

Eu estou traduzindo a atualização do jogo no momento, talvez daqui alguns eu acabe e coloque aqui.

**Comment by hlcbump** [comment]
Olá, eu quero contribuir para a tradução dessa nova atualização, porém estou tendo certas dificuldades, se alguém puder me explicar o básico de como tudo isso funciona ficarei agradecido.

**Comment by Hokys** [comment]
> Olá, eu quero contribuir para a tradução dessa nova atualização, porém estou tendo certas dificuldades, se alguém puder me explicar o básico de como tudo isso funciona ficarei agradecido.

Olá hlcbump, para começar a traduzir você pode verificar e baixar os programas necessários na página inicial: https://github.com/Ludeon/RimWorld-PortugueseBrazilian/. Primeiramente, se você não tem familiaridade com o Github, aconselho fortemente o download do Github desktop para baixar a tradução e dar "Pull requests" (que é o meio onde você envia suas alterações para serem revisadas e aprovadas) das suas alterações nela. O segundo programa a ser instalado é o Atom, que irá auxiliar na edição dos textos, em conjunto com o pacote beautify, para a organização e padronização.

Se tiver qualquer dúvida sobre como baixar a tradução e dar "Pull requests", pode responder este tópico. Só mais uma coisa, peço que ainda não comece a traduzir, pois estou terminando a tradução de algumas coisas do jogo base e da expansão. Quando eu colocar todos os arquivos da tradução atualizados aqui, eu irei avisar neste tópico. Iria gerar uma confusão na hora de postar a tradução se duas pessoas traduzissem ao mesmo tempo, as mesmas coisas...

**Comment by hlcbump** [comment]
> > Olá, eu quero contribuir para a tradução dessa nova atualização, porém estou tendo certas dificuldades, se alguém puder me explicar o básico de como tudo isso funciona ficarei agradecido.
> 
> Olá hlcbump, para começar a traduzir você pode verificar e baixar os programas necessários na página inicial: https://github.com/Ludeon/RimWorld-PortugueseBrazilian/. Primeiramente, se você não tem familiaridade com o Github, aconselho fortemente o download do Github desktop para baixar a tradução e dar "Pull requests" (que é o meio onde você envia suas alterações para serem revisadas e aprovadas) das suas alterações nela. O segundo programa a ser instalado é o Atom, que irá auxiliar na edição dos textos, em conjunto com o pacote beautify, para a organização e padronização.
> 
> Se tiver qualquer dúvida sobre como baixar a tradução e dar "Pull requests", pode responder este tópico. Só mais uma coisa, peço que ainda não comece a traduzir, pois estou terminando a tradução de algumas coisas do jogo base e da expansão. Quando eu colocar todos os arquivos da tradução atualizados aqui, eu irei avisar neste tópico. Iria gerar uma confusão na hora de postar a tradução se duas pessoas traduzissem ao mesmo tempo, as mesmas coisas...

Bem, já tenho todos os programas necessários (Github Desktop e o Atom com o beautify), agora estou com um pouco de duvida em questão a esses "pull requests" e todo o processo do desenvolvimento da tradução em si. Em questão a tradução que você já esta fazendo pode ficar tranquilo, mas, caso venha alguma atualização futura que necessite de mais tradutores estarei a disposição!

**Comment by Hokys** [comment]
Obrigado por entender! Bom, primeiramente você irá ter de criar uma cópia (Fork) do projeto da tradução, pois você poderá alterar sua cópia e depois enviar (Pull request) para o projeto original (aconselho criar a cópia depois que eu atualizar a tradução). Para criar a cópia vá até a página inicial do projeto e clique no "Fork" (terceiro ícone), e siga os passos para criar a cópia para seu usuário. Após ter criado um "Fork", abra o Github desktop, e entre com sua conta, em seguida você irá clicar na seguinte opção: Clone a Repository, e depois colar a URL do "Fork" que está na sua conta, por exemplo, o meu é https://github.com/Hokys/RimWorld-PortugueseBrazilian. Depois de feito tudo isso, você cairá na página inicial do Github desktop, no topo dela, abaixo de "File" vai estar escrito "Current repository", clique nele e depois com o botão esquerdo do mouse, clique em "RimWorld-PortugueseBrazilian", em seguida clique em "Open in Atom". Com o Atom aberto, você irá realizar as alterações na tradução, basta ir abrindo as pastas e ir traduzindo os arquivos .xml. Para traduzir é bem simples, em cima da frase a ser traduzida existe a frase original em inglês que vem acompanhada de !-- EN: "Frase em inglês aqui", e então abaixo da frase em inglês você irá colocar a tradução que fica entre os simbolos > e < depois é só ir salvando as alterações no próprio Atom. Depois de ter feito todas as alterações, vá para o Github desktop e na parte inferior esquerda você irá ver dois espaços em branco com a imagem do seu usuário do lado, essa é a parte da descrição das alterações feitas. Em "Summary" você colocará um título, geralmente colocará a versão da tradução também, e em "Description" colocará as alterações feitas, depois clique em Commit to master para enviar as alterações para seu "Fork". No seu "Fork" (exemplo: https://github.com/Hokys/RimWorld-PortugueseBrazilian), clique em "New pull request" para enviar as suas alterações para o projeto original. Espero que tenha conseguido entender, qualquer dúvida estou à disposição.

**Comment by Hokys** [comment]
Mais uma coisa, não precisa esperar para traduzir atualizações futuras. A tradução atual ainda não está cem por cento coesa, existem erros de digitação nela, e várias histórias de colonos faltando. Então se quiser começar a traduzir assim que eu terminar aqui, sinta-se à vontade.

**Comment by hlcbump** [comment]
> Obrigado por entender! Bom, primeiramente você irá ter de criar uma cópia (Fork) do projeto da tradução, pois você poderá alterar sua cópia e depois enviar (Pull request) para o projeto original (aconselho criar a cópia depois que eu atualizar a tradução). Para criar a cópia vá até a página inicial do projeto e clique no "Fork" (terceiro ícone), e siga os passos para criar a cópia para seu usuário. Após ter criado um "Fork", abra o Github desktop, e entre com sua conta, em seguida você irá clicar na seguinte opção: Clone a Repository, e depois colar a URL do "Fork" que está na sua conta, por exemplo, o meu é https://github.com/Hokys/RimWorld-PortugueseBrazilian. Depois de feito tudo isso, você cairá na página inicial do Github desktop, no topo dela, abaixo de "File" vai estar escrito "Current repository", clique nele e depois com o botão esquerdo do mouse, clique em "RimWorld-PortugueseBrazilian", em seguida clique em "Open in Atom". Com o Atom aberto, você irá realizar as alterações na tradução, basta ir abrindo as pastas e ir traduzindo os arquivos .xml. Para traduzir é bem simples, em cima da frase a ser traduzida existe a frase original em inglês que vem acompanhada de !-- EN: "Frase em inglês aqui", e então abaixo da frase em inglês você irá colocar a tradução que fica entre os simbolos > e < depois é só ir salvando as alterações no próprio Atom. Depois de ter feito todas as alterações, vá para o Github desktop e na parte inferior esquerda você irá ver dois espaços em branco com a imagem do seu usuário do lado, essa é a parte da descrição das alterações feitas. Em "Summary" você colocará um título, geralmente colocará a versão da tradução também, e em "Description" colocará as alterações feitas, depois clique em Commit to master para enviar as alterações para seu "Fork". No seu "Fork" (exemplo: https://github.com/Hokys/RimWorld-PortugueseBrazilian), clique em "New pull request" para enviar as suas alterações para o projeto original. Espero que tenha conseguido entender, qualquer dúvida estou à disposição.

Eu entendi perfeitamente, muito obrigado. Porém estou com dúvida no seguinte, para trabalhar nas futuras atualizações eu devo pegar o arquivo do .xml no diretório do jogo atualizado ou aqui no projeto do github? Pois eu vi que a versão que ta aqui é 1.0.2282 e já estamos na 1.1.2552 com a expansão royalt, obrigado.

**Comment by Hokys** [comment]
Eu estou atualizando para a versão 1.1.2552 com a Royalty, quando eu colocar a tradução atualizada aqui, você pode dar "Fork" na versão atualizada e começar a traduzir, recomendo sempre pegar a tradução por aqui, pois os desenvolvedores pegam daqui para colocar no jogo. Por pegar o arquivo ".xml" você quer dizer pegar um por um? Se for, não precisa pegar um por um, quando você dá "Fork" no projeto original, todos os arquivos da tradução vão para seu repositório (seu perfil), aí você tem acesso a todos os arquivos a partir do Atom aberto no Github desktop, então é só ir abrindo as pastas no Atom e selecionando os ".xml" para traduzir.

**Comment by hlcbump** [comment]
Ahh ta agora eu entendi, muito obrigado!

**Comment by hlcbump** [comment]
> Eu estou atualizando para a versão 1.1.2552 com a Royalty, quando eu colocar a tradução atualizada aqui, você pode dar "Fork" na versão atualizada e começar a traduzir, recomendo sempre pegar a tradução por aqui, pois os desenvolvedores pegam daqui para colocar no jogo. Por pegar o arquivo ".xml" você quer dizer pegar um por um? Se for, não precisa pegar um por um, quando você dá "Fork" no projeto original, todos os arquivos da tradução vão para seu repositório (seu perfil), aí você tem acesso a todos os arquivos a partir do Atom aberto no Github desktop, então é só ir abrindo as pastas no Atom e selecionando os ".xml" para traduzir.

Ahh ta, agora eu entendi!

**Comment by Hokys** [comment]
> Ahh ta, agora eu entendi!

Disponha! Se houver mais alguma dúvida, é só comentar.

**Comment by PhilippusBR** [comment]
Opa, muito legal pessoal, feliz por saber que a tradução esta ativa ainda.

Pretendo me integrar ao projeto também e ajudar nas traduções das histórias e demais partes faltantes. Li as postagens e já deixei tudo pronto para os trabalhos.
Vou aguardar o update do Hokys então.

Vamos manter o contato e ir combinando depois quem fará qual parte quem sabe.

Uma coisa... o manual de boas práticas não está acessível. Seria muito bom ele estar acessível com um tutorial de como configurar tudo e iniciar os trabalhos, para novos interessados. As postagens do Hokys foram minha salvação, no entanto demorei para achar aqui. Abraço

**Comment by Hokys** [comment]
> Opa, muito legal pessoal, feliz por saber que a tradução esta ativa ainda.
> 
> Pretendo me integrar ao projeto também e ajudar nas traduções das histórias e demais partes faltantes. Li as postagens e já deixei tudo pronto para os trabalhos.
> Vou aguardar o update do Hokys então.
> 
> Vamos manter o contato e ir combinando depois quem fará qual parte quem sabe.
> 
> Uma coisa... o manual de boas práticas não está acessível. Seria muito bom ele estar acessível com um tutorial de como configurar tudo e iniciar os trabalhos, para novos interessados. As postagens do Hokys foram minha salvação, no entanto demorei para achar aqui. Abraço
> 
> Uma dúvida, como aplico esta função Beautify no Atom?

Olá PhillippusBR, muito obrigado pelo interesse em contribuir com a tradução, sua ajuda, assim como a do hlcbump, serão de grande importância. Eu estou um pouco ocupando ultimamente, então ficando conciliar o tempo livre com a tradução, mas espero que daqui alguns dias eu acabe ela, e vocês possam começar a traduzir. Sobre o beautifier, você só precisa ir em configurações no Atom e em seguida em "packages" para ativar, normalmente quando você clica para baixar, ela se ativa automaticamente no Atom, mas é bom conferir!

**Comment by PhilippusBR** [comment]
Ao verificar o Atom em "file>settings>packages" eu não encontrei o "beautifier" instalado. Então cliquei em "install" e pesquisei por "beautifier", mas retorna com muitos pacotes chamados assim de "beautifier"... logo não sei qual deveria instalar. Existe alguma forma melhor ou mais correta de baixar e instalar este pacote?

**Comment by Hokys** [comment]
> Ao verificar o Atom em "file>settings>packages" eu não encontrei o "beautifier" instalado. Então cliquei em "install" e pesquisei por "beautifier", mas retorna com muitos pacotes chamados assim de "beautifier"... logo não sei qual deveria instalar. Existe alguma forma melhor ou mais correta de baixar e instalar este pacote?

Olá, para baixar o beautify clique [aqui](https://atom.io/packages/atom-beautify), eu atualizei o README.md, porém ainda não fiz upload. Eu estava pensando aqui... Eu creio que vou demorar para atualizar todos os arquivos para a versão mais recente do jogo (1.1.2560), então vou fazer upload aqui no repositório oficial, para que possamos nos ajudar a traduzir (e que vocês já possam começar imediatamente), porém, tenham em mente que ainda faltam arquivos, tanto da expansão, quanto do jogo base, e eu vou ir colocando eles periodicamente. Eu queria aproveitar o momento para perguntar se você tem alguma rede social em que possamos nos comunicar com mais facilidade, por exemplo o Discord.

**Comment by PhilippusBR** [comment]
Obrigado Hokys

Agora sim, estou com o atom-beautify instalado. Meu usuário no discord é #2384, nick igual aqui Philippus. Tenho um servidor no discord caso queiram utilizar segue o convite https://discord.gg/QNeECwG

Que legal que vc já vai ir atualizando os arquivos aqui, estamos neste momento de lançamento de DLC e os DEVs estão upando muitos hotfix, seria interessante utilizar este momento para uparmos a tradução.

Esta seria minha próxima pergunta, como faço para atualizar os arquivos da tradução, digamos assim, agregando aquilo que já esta traduzido com os novos textos em inglês, referente aos upgrades e DLC. Estou com bastante tempo livre e com bastante vontade de ajudar a tradução.

**Comment by ronaldiux** [comment]
Boa noite,
eu ingressei no projeto faz um tempo, mas por motivos pessoas ( agora sou pai e terminei a facul agora) vou voltar a traduzir, assim que voce terminar a atualização, eu tambem vou ajudar no projeto.

**Comment by PhilippusBR** [comment]
> Boa noite,
> eu ingressei no projeto faz um tempo, mas por motivos pessoas ( agora sou pai e terminei a facul agora) vou voltar a traduzir, assim que voce terminar a atualização, eu tambem vou ajudar no projeto.

Já estamos traduzindo @ronaldiux 
Add eu e o Hokys no discord, para a gente combinar. 

User do Hokys #9017
User meu #2384

**Comment by ronaldiux** [comment]
Nao consegui enviar pedido, se poderem tentar me enviar
RonaldoJr#6098
